# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build34:
    docker:
      - image: circleci/python:3.4

    working_directory: ~/luminoth

    steps:
      - checkout
      - restore_cache:
          key: deps1-python3.4-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install flake8

      - save_cache:
          key: deps1-python3.4-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: run linter
          command: |
            . venv/bin/activate
            flake8 luminoth

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s luminoth -p "*_test.py"

  build27:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/luminoth

    steps:
      - checkout
      - restore_cache:
          key: deps1-python2.7-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            pip install virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install flake8

      - save_cache:
          key: deps1-python2.7-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: run linter
          command: |
            . venv/bin/activate
            flake8 luminoth

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s luminoth -p "*_test.py"

workflows:
  version: 2
  build_multiple_versions:
    jobs:
      - build27
      - build34:
          requires:
            - build27
